openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /pets/{id}:
    get:
      tags:
        - pet-controller
      operationId: getPet
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                oneOf:
                  - $ref: "#/components/schemas/Cat"
                  - $ref: "#/components/schemas/Dog"
components:
  schemas:
    Cat:
      type: object
      allOf:
        - $ref: "#/components/schemas/Pet"
        - type: object
          properties:
            lives:
              type: integer
              format: int32
    Dog:
      type: object
      allOf:
        - $ref: "#/components/schemas/Pet"
        - type: object
          properties:
            age:
              type: integer
              format: int32
    Pet:
      type: object
      properties:
        type:
          type: string
          enum:
            - DOG
            - CAT
        id:
          type: integer
          format: int32
        name:
          type: string
      discriminator:
        propertyName: type
        mapping:
          DOG: "#/components/schemas/Dog"
          CAT: "#/components/schemas/Cat"
