/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
export interface Pet {
  id?: number;
  name?: string;
}





  export const getPet = <TData = AxiosResponse<Pet>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/pets/${id}`,options
    );
  }

export type GetPetResult = AxiosResponse<Pet>
