/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
export type PetType = typeof PetType[keyof typeof PetType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PetType = {
  DOG: 'DOG',
  CAT: 'CAT',
} as const;

export interface Pet {
  id?: number;
  name?: string;
  type?: PetType;
}

export type DogType = typeof DogType[keyof typeof DogType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DogType = {
  DOG: 'DOG',
} as const;

export type DogAllOf = {
  age?: number;
};

export type Dog = Pet & DogAllOf & {
  type: DogType;
};

export type CatType = typeof CatType[keyof typeof CatType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CatType = {
  CAT: 'CAT',
} as const;

export type CatAllOf = {
  lives?: number;
};

export type Cat = Pet & CatAllOf & {
  type: CatType;
};





  export const getPet = <TData = AxiosResponse<Pet>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/pets/${id}`,options
    );
  }

export type GetPetResult = AxiosResponse<Pet>
